-- BCV Daily Rates Table
-- Based on the user's Excel image, containing rates (Bs/Currency) for multiple currencies.
-- We use the 'ASK' (Venta) price as the standard reference rate.

create table if not exists public.bcv_quotes (
  id bigint generated by default as identity primary key,
  date date not null unique, -- "Fecha Valor" from the Excel (Unique per day)
  
  -- Currencies found in the provided image (Bs./M.E. Venta column)
  usd numeric, -- United States Dollar
  eur numeric, -- Euro
  cny numeric, -- Chinese Yuan
  try_lira numeric, -- Turkish Lira (renamed from try to avoid reserved keyword issues)
  rub numeric, -- Russian Ruble
  cad numeric, -- Canadian Dollar
  inr numeric, -- Indian Rupee
  jpy numeric, -- Japanese Yen
  ars numeric, -- Argentine Peso
  brl numeric, -- Brazilian Real
  clp numeric, -- Chilean Peso
  cop numeric, -- Colombian Peso
  uyu numeric, -- Uruguayan Peso
  pen numeric, -- Peruvian Sol
  bob numeric, -- Bolivian Boliviano
  mxp numeric, -- Mexican Peso
  cuc numeric, -- Cuban Convertible Peso
  nio numeric, -- Nicaraguan Córdoba
  dop numeric, -- Dominican Peso
  ttd numeric, -- Trinidad and Tobago Dollar
  ang numeric, -- Netherlands Antillean Guilder
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Security Policies
alter table public.bcv_quotes enable row level security;

-- Allow anyone to read
create policy "Enable read access for all users"
on public.bcv_quotes
for select
using (true);

-- Allow service role to insert/update
create policy "Enable insert for service role only"
on public.bcv_quotes
for insert
with check (true);

create policy "Enable update for service role only"
on public.bcv_quotes
for update
using (true);

-- ==========================================
-- NEW FEATURES: NEWS & ANALYSIS
-- ==========================================

-- P2P Market History Log
create table if not exists public.p2p_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  platform text not null, -- 'binance', 'bybit'
  type text not null, -- 'buy', 'sell'
  price numeric not null,
  advertiser text,
  volume numeric, -- Available amount or limit max
  currency text default 'VES'
);

alter table public.p2p_history enable row level security;
create policy "Public read p2p_history" on public.p2p_history for select using (true);
create policy "Service insert p2p_history" on public.p2p_history for insert with check (true);

-- Crypto News Feed
create table if not exists public.news_feed (
  id bigint generated by default as identity primary key,
  published_at timestamp with time zone not null,
  title text not null,
  url text not null unique,
  source text not null,
  sentiment_score float, -- -1.0 (Negative) to 1.0 (Positive)
  summary text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.news_feed enable row level security;
create policy "Public read news_feed" on public.news_feed for select using (true);
create policy "Service insert news_feed" on public.news_feed for insert with check (true);

-- AI Market Reports
create table if not exists public.market_reports (
  id bigint generated by default as identity primary key,
  date date default current_date,
  report_type text not null, -- 'daily_brief', 'prediction', 'local_analysis'
  title text,
  content text not null,
  sentiment_label text, -- 'bullish', 'bearish', 'neutral'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.market_reports enable row level security;
create policy "Public read market_reports" on public.market_reports for select using (true);
create policy "Service insert market_reports" on public.market_reports for insert with check (true);
